defaults:
  - sac_state
  - override /wm: infonce
  - _self_

checkpoint_dir: ./runs/sac_taco_state/finger_turn_hard
auxiliary:
  enabled: true
  wm:
    enabled: true
    horizon: 3
    projection_dim: 50
    hidden_dim: 256
  reward_prediction:
    enabled: true
